### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/php-multihash#1]
Hey @Fil!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by Fil** [comment]
Obviously if @jbenet is in I'm ok to transfer it

But I must say that upon first look the multiformat org profile doesn't look very engaging. It would help if there was an icon, a readme, an org charter or desc, and more than 1 person under "people".

**Comment by Fil** [comment]
Transfer currently fails with “You don’t have admin rights to multiformats.” Am I clicking on the wrong button?

**Comment by RichardLitt** [comment]
@Fil Good feedback. Working on the multiformats branding as fast as I can. 

Huh, that's weird. One second, look at it.

**Comment by Fil** [comment]
![capture d ecran 2016-08-05 20 12 24](https://cloud.githubusercontent.com/assets/7001/17446313/022dc966-5b49-11e6-9701-8af79888427a.png)

**Comment by RichardLitt** [comment]
Sorry about this - figuring it out. Added you as a member of the group, will add you as an admin of this repo as soon as it is transferred (if you still want to! :))

**Comment by RichardLitt** [comment]
That doesn't seem right. Weird? Maybe you should transfer it to me, and then I'll transfer it to the org. (Or to @jbenet, because you may not know me all that well).

**Comment by jbenet** [comment]
Hello! o/ yeah pls transfer to multihash org if works for you. 

It's annoying that github doesnt let you have it without admin rights on whole org. the only reason we're not directly giving admin rights to everyone is that then we'd end up with dozens of admins with powers across all org and that may not be a good idea (have seen it backfire).

Our rough protocol is going to be this, i think it works to cover all permissions/process issues, but may have bugs:

### "Transfer repo to Org" protocol
- [ ] Org Admin adds Repo Author as member to the Org
- [ ] transfer Repo to the Org (2 steps because of how github works):
  - [ ] Author transfers repo to Org Admin
  - [ ] Org Admin transfers repo to Org
- [ ] Org Admin adds Repo Author as collaborator with "Admin" privs on the Repo
  - [ ] edit readme to name Repo Author as "Maintainer" of the Repo (unless they dont want to be)
  - [ ] let Maintainer (Repo Author) know they can add whoever they want, do whatever, etc. 
- [ ] Give the "Admin Team" in the Org permission to the Repo (unless maintainer request not to)

Notes:
- Maybe create a "Responsibilities and Powers of Maintainers" doc in github.com/ipfs/community/ ?
- Don't need to add Author/Maintainer to "Admin Team". This is a separate decision (i.e. are they administrating the entire org?), as it would give them privileges on ALL repos and many maintainers would not like maintainers of other repos to have full powers over theirs, etc.

**Comment by jbenet** [comment]
@RichardLitt maybe worth putting the "Transfer repo to Org" Protocol somewhere in ipfs/community too? that way everyone can be on the same page about how we do this. maybe worth writing a paragraph or two motivating why (like your first post on this issue)

**Comment by Fil** [comment]
"This repository is being transferred to @RichardLitt."

Sorry for the delay I was having a beer watching the sun set on Britanny's westernmost coast.

**Comment by jbenet** [comment]
@Fil thank you! no rush! and that sounds fantastic and wonderful. Pictures? I think this issue needs pictures.

**Comment by RichardLitt** [comment]
> Sorry for the delay I was having a beer watching the sun set on Britanny's westernmost coast. 

That is the best reason I have ever heard of. 

Done! Gave you admin rights to this repo. It's still yours. Thanks!

**Comment by Fil** [comment]
this issue was more work than the code itself :)

![photo](https://cloud.githubusercontent.com/assets/7001/17448238/93426c2c-5b53-11e6-88a7-4d90cd427644.JPG)

**Comment by RichardLitt** [comment]
Looks beautiful!
